### ISSUE TITLE
AutoScale Stack(Only AutoScaling) issue

### ISSUE THREAD

**Issue by hideokamoto** [amimoto-ami/c3-cloudfront-clear-cache#15]
```
[14-Dec-2016 09:02:18 UTC] PHP Fatal error:  Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 6: Could not resolve host: wp-content [url] https://wp-content/uploads/2016/12/shifter_-20161214090211.png' in phar:///var/www/html/wp-content/plugins/c3-cloudfront-clear-cache/aws.phar/Guzzle/Http/Curl/CurlMulti.php:359
Stack trace:
#0 phar:///var/www/html/wp-content/plugins/c3-cloudfront-clear-cache/aws.phar/Guzzle/Http/Curl/CurlMulti.php(292): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Curl\CurlHandle), Array)
#1 phar:///var/www/html/wp-content/plugins/c3-cloudfront-clear-cache/aws.phar/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Curl\CurlHandle), Array)
#2 phar:///var/www/html/wp-content/plugins/c3-cloudfront-clear-cache/aws.phar/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
#3 phar:///var/www/html/wp-content/plugins/c3-cloudfront-clear-cache/aw in phar:///var/www/html/wp-content/plugins/c3-cloudfront-clear-cache/aws.phar/Aws/Common/Client/AbstractClient.php on line 258
```

**Comment by hideokamoto** [comment]
When Image file upload.

**Comment by hideokamoto** [comment]
Invalidation works.

**Comment by hideokamoto** [comment]
Need setup Nephila Clavata plugin
